### ISSUE TITLE
in-file vs. in_file

### ISSUE THREAD

**Issue by CWBudde** [GoobyCorp/AB2E#4]
While I'm not a python expert, I wonder whether
`	parser.add_argument("in-file", type=str, help="The input file"`
would not cause this line:
`decrypt_save_file(args.in_file, args.out_file, args.index_file)`
to not find the "in_file" (as it is registered as "in-file")?

**Comment by GoobyCorp** [comment]
The dash gets turned into an underscore.

On June 17, 2020 11:44:13 PM EDT, Christian Budde <notifications@github.com> wrote:
>While I'm not a python expert, I wonder whether
>`	parser.add_argument("in-file", type=str, help="The input file"`
>would not cause this line:
>`decrypt_save_file(args.in_file, args.out_file, args.index_file)`
>to not find the "in_file" (as it is registered as "in-file")?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GoobyCorp/AB2E/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
