### ISSUE TITLE
Save File Names are Changed

### ISSUE THREAD

**Issue by angularPublic** [GoobyCorp/AB2E#5]
ALL_FILES = [
"8DA4F614BD109FD64248704E48E720719DBA53061539CB4C46B6ECBA475C6E5C"
"8DFFF74AF71428AEEB5E6CBED03BBB330319126853C4E4D8A924F925B148F80C",
"9162F9A329E976EBD133E8013D59FECFDF5A21ED701FB2AF1246D847F52756A2",
"91C8ECDC2923E2A7E9EC4817C7D6D5FBF25E05BFB2402B3714ABFCD5A3C001BF",
"925C1B5A59908E93964655A3FA13FE097240CE39443A396871544E0B54A2E943",
"AB890F85A4342A8E957A9292A2B38423C8C9F511F59631837EB4EAF722174C14",
"B2BD44808B01FEEE6C1B8917B851CEF64978B5560EA10368424F7EE9196DF6BA",
"B4F59D3E9582F13D98B85102B4003E377A9434837B71846F44C05637D2613FA1",
#"B530BFB9C225DF26B7D4DFE3E5808F16FB5ACFF9DC3481BA677EC62C85E3BF62", <-- File never encrypted,  decrypt = boom
"D786BE26B3CB0A84708C126F16082DE2CFCFBD4BDB709C2A0963FDB0B9879923"
]

**Comment by GoobyCorp** [comment]
You have duplicates in there

**Comment by angularPublic** [comment]
Updated.

**Comment by GoobyCorp** [comment]
Where did you find these? I would like to know how to generate them, you can see in gen_key_hash how they were generated before.

EDIT: They appear to be generated the same way, I just don't know the actual names that are hashed to get those.

**Comment by angularPublic** [comment]
These files are in my save folder. I used your program not knowing what is does but noticed few files are not decrypted. And after the change, program decrypted all the files. BTW, Good work. 

![image](https://user-images.githubusercontent.com/11204877/85913367-d36b8480-b7f9-11ea-9e47-53a169946199.png)

**Comment by angularPublic** [comment]
[AB2E_New.zip](https://github.com/GoobyCorp/AB2E/files/4839911/AB2E_New.zip)

BTW, I have found a different source from this repo. FYI.

**Comment by GoobyCorp** [comment]
> BTW, I have found a different source from this repo. FYI.

Not sure what you mean by that...

**Comment by angularPublic** [comment]
From here: https://gbatemp.net/threads/release-ab2e-angry-birds-2-editor.485651/

**Comment by GoobyCorp** [comment]
That's fine, I was thinking someone was taking credit for it.

**Comment by angularPublic** [comment]
:-)
